# Generated by Django 5.1 on 2024-08-28 02:50

import django.db.models.deletion
import prose.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', prose.fields.DocumentContentField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content', models.ManyToManyField(to='lessons.lessoncontent')),
            ],
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='text',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lessons.textcontent'),
        ),
    ]
