# Generated by Django 5.1 on 2024-08-28 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('prose', '0002_alter_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncontent',
            name='text',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prose.document'),
        ),
    ]
