# Generated by Django 5.1 on 2024-08-28 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lessoncontent_text'),
        ('prose', '0002_alter_document_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='content',
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='text',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='prose.document'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='prose.document'),
        ),
    ]
