# Generated by Django 5.1 on 2024-08-28 03:04

import prose.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_remove_lesson_content_alter_lessoncontent_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=prose.fields.RichTextField(null=True),
        ),
    ]
