# Generated by Django 5.1 on 2024-08-28 21:30

import prose.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_lesson_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', prose.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='TextContent',
        ),
        migrations.RemoveField(
            model_name='lessoncontent',
            name='text',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='content',
        ),
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.ManyToManyField(to='lessons.lessoncontent'),
        ),
    ]
