# Generated by Django 5.1 on 2024-08-28 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_lessoncontent_content_type_alter_textblock_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='exercise',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.exerciseblock'),
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.uploadedimageblock'),
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='text',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.textblock'),
        ),
    ]
