# Generated by Django 5.1 on 2024-08-29 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_lessoncontent_exercise_lessoncontent_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
