# Generated by Django 5.1 on 2024-09-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_lessoncontent_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimageblock',
            name='caption',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
