# Generated by Django 5.1 on 2024-09-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_alter_uploadedimageblock_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimageblock',
            name='caption',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
