# Generated by Django 5.1 on 2024-09-04 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_alter_uploadedimageblock_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lessoncontent',
            name='exercise',
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='table',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.tableblock'),
        ),
        migrations.DeleteModel(
            name='ExerciseBlock',
        ),
    ]
