# Generated by Django 5.1 on 2024-09-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_tableblock_remove_lessoncontent_exercise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('data', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tableblock',
            name='data',
        ),
        migrations.AddField(
            model_name='tableblock',
            name='cells',
            field=models.ManyToManyField(to='lessons.tablecell'),
        ),
    ]
