# Generated by Django 5.1 on 2024-09-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_tablecell_remove_tableblock_data_tableblock_cells'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncontent',
            name='content_type',
            field=models.CharField(blank=True, choices=[('TXT', 'Text'), ('IMG', 'Image'), ('EXR', 'Exercise'), ('TBL', 'Table')], max_length=3),
        ),
    ]
